name: Publish Docker image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker
    runs-on: ubutu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
